# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Attractor": "00_attractor.ipynb",
         "rotation_matrix": "00_attractor.ipynb",
         "rotate": "00_attractor.ipynb",
         "RouletteCurve": "00_attractor.ipynb"}

modules = ["core.py"]

doc_url = "https://generic-github-user.github.io/attractors/"

git_url = "https://github.com/generic-github-user/attractors/tree/main/"

def custom_doc_links(name): return None
